swagger: '2.0'
info:
  title: Bank Argent API documentation - Phase 2 
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Accounts API
      description: API for fetching a user accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
                month:
                  type: string
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            $ref: '#/definitions/UserAccounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/:accountId/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching a user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
                month:
                  type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/UserTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/:accountId/transactions/:transactionId/notes:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: Add notes to a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
                value:
                  type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/UserTransaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: Delete notes from transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/UserTransaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/accounts/:accountId/transactions/:transactionId/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: Modify a category from transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
                value:
                  type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction retrieved successully
          schema:
            $ref: '#/definitions/UserTransaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UserAccounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            amount:
              type: number
            numberOfTransactions:
              type: integer
            balanceType:
              type: string
  UserTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
            amount:
              type: number
            date:
              type: string
              format: date
            type:
              type: string
            category:
              type: string
  UserTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          description:
            type: string
          amount:
            type: number
          date:
            type: string
            format: date
          type:
            type: string
          category:
            type: string
          notes:
            type: string



